version: "3.7"

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  redis:
    image: redis
    command: redis-server
    volumes:
      - "./lib/redis/data:/var/lib/redis/data"
  web:
    build: .
    command: foreman start -f Procfile.dev -p 3000
    volumes:
      - .:/myapp
      - type: tmpfs
        target: /project/tmp/pids/
    ports:
      - "3000:3000"
      - "35729:35729"
    depends_on:
      - db
      - redis
